added healthReport data type, query, resolver
matthewjwhitney/health-quiz-server pull request #3
Opened 2021-01-03 21:59 UTC by austenm

2021-01-03 22:06 UTC, matthewjwhitney requested changes

2021-01-03 22:06 UTC, matthewjwhitney commented on src/index.js
> +    healthReport: HealthReport
remove this for now because we haven't built the query and resolver for this yet.

2021-01-03 22:58 UTC, matthewjwhitney approved these changes

2021-01-03 22:59 UTC, matthewjwhitney commented
in the description of pull request you need to include the issue that it closes so in this case "closes #1"

2021-01-03 23:37 UTC, matthewjwhitney approved these changes

2021-01-04 18:55 UTC, mareklubomirski approved these changes

2021-01-04 18:58 UTC, merged

2021-01-04 19:02 UTC, matthewjwhitney commented
Hell yes! @austenm got his first PR merged!